# Generated by Django 3.1.3 on 2021-08-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_auto_20210830_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authorized',
            field=models.BooleanField(default=False),
        ),
    ]
