# Generated by Django 3.1.3 on 2021-09-01 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_user_authorized'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_in_chat',
            new_name='in_authorizing',
        ),
    ]
