# Generated by Django 3.1.3 on 2021-09-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_auto_20210901_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
